configured_endpoints: 28
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/iris%2Firis-connector-1362ef12c16dfa7dac90b86a196e0cf1fab1b60d1f9fdfcf954b247cef401aaf.yml
openapi_spec_hash: e6c3edde6b77857c0de9be00aeafd3a6
config_hash: 8c8586899c55da921099af5b73246c3b
